server:
  port: 88

# mysql
spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery: # 是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator: # 路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        - id: coupon_route
          uri: lb://coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - StripPrefix=1
        - id: member_route
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: ware_route
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - StripPrefix=1

seata:
  enabled: false